webtalk_init -webtalk_dir C:/Users/iiHAK/Downloads/ArcProj1M1-main/ArcProj1M1-main - Copy/ArcProj1M1/ArcProj1M1.sim/sim_1/behav/xsim/xsim.dir/Simulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 10 01:21:47 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b40517a1ad15b278862c1b09719ad84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fa36c5cec3c64c7ab29b05cbd0416c97" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "615 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7644_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3516905702 -regid "" -xml C:/Users/iiHAK/Downloads/ArcProj1M1-main/ArcProj1M1-main - Copy/ArcProj1M1/ArcProj1M1.sim/sim_1/behav/xsim/xsim.dir/Simulation_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/iiHAK/Downloads/ArcProj1M1-main/ArcProj1M1-main - Copy/ArcProj1M1/ArcProj1M1.sim/sim_1/behav/xsim/xsim.dir/Simulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/iiHAK/Downloads/ArcProj1M1-main/ArcProj1M1-main - Copy/ArcProj1M1/ArcProj1M1.sim/sim_1/behav/xsim/xsim.dir/Simulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
